// import mongoose from 'mongoose';
// import env from '../utils/evn.js';
// import ReportingModel from './ReportingModels.js';

// TO USE THIS RUN : node src/app/server/models/reportingSeed.js

// const mainPageSeed = async () => {
//   try {
//     await mongoose.connect(env('MONGODB_URI'));
//     console.log('✅ Connected to MongoDB');

//     const reportingEN = [
//       {
//         title: 'Water to the Grey Zone',
//         item: 'Collected:',
//         total: '35768',
//         currency: 'UAH',
//         term: 'Implementation Period:',
//         days: '10',
//         period: 'days',
//         comments: 'Reviews:',
//         quantity: '5',
//         image: '',
//         type: 'reporting',
//         language: 'en',
//       },
//       {
//         title: 'Water to the Grey Zone-2',
//         item: 'Collected:',
//         total: '35768',
//         currency: 'UAH',
//         term: 'Implementation Period:',
//         days: '10',
//         period: 'days',
//         comments: 'Reviews:',
//         quantity: '5',
//         image: '',
//         type: 'reporting',
//         language: 'en',
//       },
//       {
//         title: 'Water to the Grey Zone-3',
//         item: 'Collected:',
//         total: '35768',
//         currency: 'UAH',
//         term: 'Implementation Period:',
//         days: '10',
//         period: 'days',
//         comments: 'Reviews:',
//         quantity: '5',
//         image: '',
//         type: 'reporting',
//         language: 'en',
//       },
//       {
//         title: 'Water to the Grey Zone-4',
//         item: 'Collected:',
//         total: '35768',
//         currency: 'UAH',
//         term: 'Implementation Period:',
//         days: '10',
//         period: 'days',
//         comments: 'Reviews:',
//         quantity: '5',
//         image: '',
//         type: 'reporting',
//         language: 'en',
//       },
//       {
//         title: 'Water to the Grey Zone-55',
//         item: 'Collected:',
//         total: '35768',
//         currency: 'UAH',
//         term: 'Implementation Period:',
//         days: '10',
//         period: 'days',
//         comments: 'Reviews:',
//         quantity: '5',
//         image: '',
//         type: 'reporting',
//         language: 'en',
//       },
//       {
//         title: 'Water to the Grey Zone-5',
//         item: 'Collected:',
//         total: '35768',
//         currency: 'UAH',
//         term: 'Implementation Period:',
//         days: '10',
//         period: 'days',
//         comments: 'Reviews:',
//         quantity: '5',
//         image: '',
//         type: 'reporting',
//         language: 'en',
//       },
//       {
//         title: 'Water to the Grey Zone-6',
//         item: 'Collected:',
//         total: '35768',
//         currency: 'UAH',
//         term: 'Implementation Period:',
//         days: '10',
//         period: 'days',
//         comments: 'Reviews:',
//         quantity: '5',
//         image: '',
//         type: 'reporting',
//         language: 'en',
//       },
//       {
//         title: 'Water to the Grey Zone-7',
//         item: 'Collected:',
//         total: '35768',
//         currency: 'UAH',
//         term: 'Implementation Period:',
//         days: '10',
//         period: 'days',
//         comments: 'Reviews:',
//         quantity: '5',
//         image: '',
//         type: 'reporting',
//         language: 'en',
//       },
//       {
//         title: 'Water to the Grey Zone-8',
//         item: 'Collected:',
//         total: '35768',
//         currency: 'UAH',
//         term: 'Implementation Period:',
//         days: '10',
//         period: 'days',
//         comments: 'Reviews:',
//         quantity: '5',
//         image: '',
//         type: 'reporting',
//         language: 'en',
//       },
//       {
//         title: 'Water to the Grey Zone Final',
//         item: 'Collected:',
//         total: '35768',
//         currency: 'UAH',
//         term: 'Implementation Period:',
//         days: '10',
//         period: 'days',
//         comments: 'Reviews:',
//         quantity: '5',
//         image: '',
//         type: 'reporting',
//         language: 'en',
//       },
//     ];

//     await ReportingModel.insertMany(reportingEN);
//     console.log('📦 Reporting inserted');

//     const collectionsUK = [
//       {
//         title: 'Вода в сіру зону',
//         item: 'Зібрано:',
//         total: '35768',
//         currency: 'грн',
//         term: 'Термін реалізаці:',
//         days: '10 ',
//         period: 'днів',
//         comments: 'Відгуків:',
//         quantity: '5',
//         image: '',
//         type: 'reporting',
//         language: 'uk',
//       },
//       {
//         title: 'Вода в сіру зону-2',
//         item: 'Зібрано:',
//         total: '35768',
//         currency: 'грн',
//         term: 'Термін реалізаці:',
//         days: '10 ',
//         period: 'днів',
//         comments: 'Відгуків:',
//         quantity: '5',
//         image: '',
//         type: 'reporting',
//         language: 'uk',
//       },
//       {
//         title: 'Вода в сіру зону-3',
//         item: 'Зібрано:',
//         total: '35768',
//         currency: 'грн',
//         term: 'Термін реалізаці:',
//         days: '10 ',
//         period: 'днів',
//         comments: 'Відгуків:',
//         quantity: '5',
//         image: '',
//         type: 'reporting',
//         language: 'uk',
//       },
//       {
//         title: 'Вода в сіру зону-4',
//         item: 'Зібрано:',
//         total: '35768',
//         currency: 'грн',
//         term: 'Термін реалізаці:',
//         days: '10 ',
//         period: 'днів',
//         comments: 'Відгуків:',
//         quantity: '5',
//         image: '',
//         language: 'uk',
//         type: 'reporting',
//       },
//       {
//         title: 'Вода в сіру зону-55',
//         item: 'Зібрано:',
//         total: '35768',
//         currency: 'грн',
//         term: 'Термін реалізаці:',
//         days: '10 ',
//         period: 'днів',
//         comments: 'Відгуків:',
//         quantity: '5',
//         image: '',
//         language: 'uk',
//         type: 'reporting',
//       },
//       {
//         title: 'Вода в сіру зону-5',
//         item: 'Зібрано:',
//         total: '35768',
//         currency: 'грн',
//         term: 'Термін реалізаці:',
//         days: '10 ',
//         period: 'днів',
//         comments: 'Відгуків:',
//         quantity: '5',
//         image: '',
//         language: 'uk',
//         type: 'reporting',
//       },
//       {
//         title: 'Вода в сіру зону-6',
//         item: 'Зібрано:',
//         total: '35768',
//         currency: 'грн',
//         term: 'Термін реалізаці:',
//         days: '10 ',
//         period: 'днів',
//         comments: 'Відгуків:',
//         quantity: '5',
//         image: '',
//         language: 'uk',
//         type: 'reporting',
//       },
//       {
//         title: 'Вода в сіру зону-7',
//         item: 'Зібрано:',
//         total: '35768',
//         currency: 'грн',
//         term: 'Термін реалізаці:',
//         days: '10 ',
//         period: 'днів',
//         comments: 'Відгуків:',
//         quantity: '5',
//         image: '',
//         language: 'uk',
//         type: 'reporting',
//       },
//       {
//         title: 'Вода в сіру зону-8',
//         item: 'Зібрано:',
//         total: '35768',
//         currency: 'грн',
//         term: 'Термін реалізаці:',
//         days: '10 ',
//         period: 'днів',
//         comments: 'Відгуків:',
//         quantity: '5',
//         image: '',
//         language: 'uk',
//         type: 'reporting',
//       },
//       {
//         title: 'Вода в сіру ост',
//         item: 'Зібрано:',
//         total: '35768',
//         currency: 'грн',
//         term: 'Термін реалізаці:',
//         days: '10 ',
//         period: 'днів',
//         comments: 'Відгуків:',
//         quantity: '5',
//         image: '',
//         language: 'uk',
//         type: 'reporting',
//       },
//     ];
//     await ReportingModel.insertMany(collectionsUK);
//     console.log('📦 Reporting inserted');

//     await mongoose.connection.close();
//     console.log('🔒 Database connection closed');
//   } catch (error) {
//     console.error('❌ Error seeding database:', error);
//     await mongoose.connection.close();
//   }
// };

// mainPageSeed();
