import mongoose from 'mongoose';
import env from '../utils/evn.js';
import ReportingsModel from './ReportingModels.js';

// TO USE THIS RUN : node src/app/server/models/reportingSeed.js

const mainPageSeed = async () => {
  try {
    await mongoose.connect(env('MONGODB_URI'));
    console.log('✅ Connected to MongoDB');

    const reportingsEN = [
      {
        title: 'Water to the Grey Zone',
        item: 'Collected:',
        total: '35768',
        currency: 'UAH',
        term: 'Implementation Period:',
        days: '10',
        period: 'days',
        comments: 'Reviews:',
        quantity: '5',
        image: '',
        type: 'reportings',
        language: 'en',
      },
      {
        title: 'Water to the Grey Zone-2',
        item: 'Collected:',
        total: '35768',
        currency: 'UAH',
        term: 'Implementation Period:',
        days: '10',
        period: 'days',
        comments: 'Reviews:',
        quantity: '5',
        image: '',
        type: 'reportings',
        language: 'en',
      },
      {
        title: 'Water to the Grey Zone-3',
        item: 'Collected:',
        total: '35768',
        currency: 'UAH',
        term: 'Implementation Period:',
        days: '10',
        period: 'days',
        comments: 'Reviews:',
        quantity: '5',
        image: '',
        type: 'reportings',
        language: 'en',
      },
      {
        title: 'Water to the Grey Zone-4',
        item: 'Collected:',
        total: '35768',
        currency: 'UAH',
        term: 'Implementation Period:',
        days: '10',
        period: 'days',
        comments: 'Reviews:',
        quantity: '5',
        image: '',
        type: 'reportings',
        language: 'en',
      },
      {
        title: 'Water to the Grey Zone-55',
        item: 'Collected:',
        total: '35768',
        currency: 'UAH',
        term: 'Implementation Period:',
        days: '10',
        period: 'days',
        comments: 'Reviews:',
        quantity: '5',
        image: '',
        type: 'reportings',
        language: 'en',
      },
      {
        title: 'Water to the Grey Zone-5',
        item: 'Collected:',
        total: '35768',
        currency: 'UAH',
        term: 'Implementation Period:',
        days: '10',
        period: 'days',
        comments: 'Reviews:',
        quantity: '5',
        image: '',
        type: 'reportings',
        language: 'en',
      },
      {
        title: 'Water to the Grey Zone-6',
        item: 'Collected:',
        total: '35768',
        currency: 'UAH',
        term: 'Implementation Period:',
        days: '10',
        period: 'days',
        comments: 'Reviews:',
        quantity: '5',
        image: '',
        type: 'reportings',
        language: 'en',
      },
      {
        title: 'Water to the Grey Zone-7',
        item: 'Collected:',
        total: '35768',
        currency: 'UAH',
        term: 'Implementation Period:',
        days: '10',
        period: 'days',
        comments: 'Reviews:',
        quantity: '5',
        image: '',
        type: 'reportings',
        language: 'en',
      },
      {
        title: 'Water to the Grey Zone-8',
        item: 'Collected:',
        total: '35768',
        currency: 'UAH',
        term: 'Implementation Period:',
        days: '10',
        period: 'days',
        comments: 'Reviews:',
        quantity: '5',
        image: '',
        type: 'reportings',
        language: 'en',
      },
      {
        title: 'Water to the Grey Zone Final',
        item: 'Collected:',
        total: '35768',
        currency: 'UAH',
        term: 'Implementation Period:',
        days: '10',
        period: 'days',
        comments: 'Reviews:',
        quantity: '5',
        image: '',
        type: 'reportings',
        language: 'en',
      },
    ];

    await ReportingsModel.insertMany(reportingsEN);
    console.log('📦 Reportings inserted');

    const collectionsUK = [
      {
        title: 'Вода в сіру зону',
        item: 'Зібрано:',
        total: '35768',
        currency: 'грн',
        term: 'Термін реалізаці:',
        days: '10 ',
        period: 'днів',
        comments: 'Відгуків:',
        quantity: '5',
        image: '',
        type: 'reportings',
        language: 'uk',
      },
      {
        title: 'Вода в сіру зону-2',
        item: 'Зібрано:',
        total: '35768',
        currency: 'грн',
        term: 'Термін реалізаці:',
        days: '10 ',
        period: 'днів',
        comments: 'Відгуків:',
        quantity: '5',
        image: '',
        type: 'reportings',
        language: 'uk',
      },
      {
        title: 'Вода в сіру зону-3',
        item: 'Зібрано:',
        total: '35768',
        currency: 'грн',
        term: 'Термін реалізаці:',
        days: '10 ',
        period: 'днів',
        comments: 'Відгуків:',
        quantity: '5',
        image: '',
        type: 'reportings',
        language: 'uk',
      },
      {
        title: 'Вода в сіру зону-4',
        item: 'Зібрано:',
        total: '35768',
        currency: 'грн',
        term: 'Термін реалізаці:',
        days: '10 ',
        period: 'днів',
        comments: 'Відгуків:',
        quantity: '5',
        image: '',
        language: 'uk',
        type: 'reportings',
      },
      {
        title: 'Вода в сіру зону-55',
        item: 'Зібрано:',
        total: '35768',
        currency: 'грн',
        term: 'Термін реалізаці:',
        days: '10 ',
        period: 'днів',
        comments: 'Відгуків:',
        quantity: '5',
        image: '',
        language: 'uk',
        type: 'reportings',
      },
      {
        title: 'Вода в сіру зону-5',
        item: 'Зібрано:',
        total: '35768',
        currency: 'грн',
        term: 'Термін реалізаці:',
        days: '10 ',
        period: 'днів',
        comments: 'Відгуків:',
        quantity: '5',
        image: '',
        language: 'uk',
        type: 'reportings',
      },
      {
        title: 'Вода в сіру зону-6',
        item: 'Зібрано:',
        total: '35768',
        currency: 'грн',
        term: 'Термін реалізаці:',
        days: '10 ',
        period: 'днів',
        comments: 'Відгуків:',
        quantity: '5',
        image: '',
        language: 'uk',
        type: 'reportings',
      },
      {
        title: 'Вода в сіру зону-7',
        item: 'Зібрано:',
        total: '35768',
        currency: 'грн',
        term: 'Термін реалізаці:',
        days: '10 ',
        period: 'днів',
        comments: 'Відгуків:',
        quantity: '5',
        image: '',
        language: 'uk',
        type: 'reportings',
      },
      {
        title: 'Вода в сіру зону-8',
        item: 'Зібрано:',
        total: '35768',
        currency: 'грн',
        term: 'Термін реалізаці:',
        days: '10 ',
        period: 'днів',
        comments: 'Відгуків:',
        quantity: '5',
        image: '',
        language: 'uk',
        type: 'reportings',
      },
      {
        title: 'Вода в сіру ост',
        item: 'Зібрано:',
        total: '35768',
        currency: 'грн',
        term: 'Термін реалізаці:',
        days: '10 ',
        period: 'днів',
        comments: 'Відгуків:',
        quantity: '5',
        image: '',
        language: 'uk',
        type: 'reportings',
      },
    ];
    await ReportingsModel.insertMany(collectionsUK);
    console.log('📦 Reportings inserted');

    await mongoose.connection.close();
    console.log('🔒 Database connection closed');
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    await mongoose.connection.close();
  }
};

mainPageSeed();
