import { Montserrat, Open_Sans } from 'next/font/google';
import clsx from 'clsx';
import { Header } from '@/modules/header';
import { Footer } from '@/modules/footer';
import { Breadcrumbs } from '@/shared/components';

import '../globals.scss';

export const metadata = {
  title: 'In Harmony',
  description: 'Generated by create next app',
};

const montserrat = Montserrat({
  subsets: ['latin', 'cyrillic'],
  weight: ['700'],
  display: 'swap',
  variable: '--font-montserrat',
});

const open_sans = Open_Sans({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '600'],
  display: 'swap',
  variable: '--font-open_sans',
});

export default function RootLayout({ children }) {
  return (
    <html lang="uk">
      <body className={clsx(open_sans.variable, montserrat.variable)}>
        <Header />
        <Breadcrumbs />
        <main>{children}</main>
        <Footer />
        <div id="modal"></div>
      </body>
    </html>
  );
}
